Repository Shin-tech25/freemarket_sample_68k, pull requests merged in 2020-02, with the labels that each got.

#1 [WIP]DB設計
  README.md
  config/routes.rb
Labels: documentation, データベース

#3 [WIP]gemが不要なデータベースモデル・マイグレーション作成
  app/models/comment.rb
  app/models/favorite.rb
  app/models/item_image.rb
  app/models/purchase.rb
  app/models/residence.rb
  db/migrate/20200213121558_create_residences.rb
  db/migrate/20200214012659_create_comments.rb
  db/migrate/20200214013409_create_purchases.rb
  db/migrate/20200214013847_create_item_images.rb
  db/migrate/20200214014114_create_favorites.rb
  db/schema.rb
  test/factories/comments.rb
  test/factories/favorites.rb
  test/factories/item_images.rb
  test/factories/purchases.rb
  test/factories/residences.rb
  test/models/comment_test.rb
  test/models/favorite_test.rb
  test/models/item_image_test.rb
  test/models/purchase_test.rb
  test/models/residence_test.rb
Labels: データベース

#2 [WIP]マイページフロント実装
  .DS_Store
  app/.DS_Store
  app/assets/.DS_Store
  app/assets/images/material/.DS_Store
  app/assets/images/material/icon/icon-01.png
  app/assets/images/material/icon/icon-02.png
  app/assets/images/material/icon/icon-03.png
  app/assets/images/material/icon/icon-04.png
  app/assets/images/material/icon/icon-search 1.png
  app/assets/images/material/icon/icon_brand.png
  app/assets/images/material/icon/icon_camera.png
  app/assets/images/material/icon/icon_category.png
  app/assets/images/material/icon/member_photo_noimage_thumb.png
  app/assets/images/material/logo/.DS_Store
  app/assets/images/material/logo/logo-white.png
  app/assets/images/material/logo/logo.png
  app/assets/images/material/pict/bg-appBanner-pict.jpg
  app/assets/images/material/pict/bg-mainVisual-pict_pc.jpg
  app/assets/images/material/pict/bg-topMiddleDl-pict.jpg
  app/assets/images/material/pict/pict-reason-01.jpg
  app/assets/images/material/pict/pict-reason-02.jpg
  app/assets/images/material/pict/pict-reason-03.jpg
  app/assets/javascripts/users.coffee
  app/assets/stylesheets/_mypage.scss
  app/assets/stylesheets/application.scss
  app/controllers/items_controller.rb
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/views/shared/_header.html.haml
  app/views/shared/_sellbtn.html.haml
  app/views/users/index.html.haml
  app/views/users/show.html.haml
  config/routes.rb
  test/controllers/users_controller_test.rb
Labels: マークアップ

#5 [WIP] トップページ実装
  .DS_Store
  app/.DS_Store
  app/assets/.DS_Store
  app/assets/images/.DS_Store
  app/assets/images/app/app-store.svg
  app/assets/images/app/google-play.svg
  app/assets/images/material/.DS_Store
  app/assets/images/material/logo/.DS_Store
  app/assets/stylesheets/_font.scss
  app/assets/stylesheets/_item_index.scss
  app/assets/stylesheets/_mixins.scss
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/index.scss
  app/views/items/_banner.html.haml
  app/views/items/_item_index.html.haml
  app/views/items/index.html.haml
Labels: マークアップ
